FROM alpine:3.15

EXPOSE 80 443 2019
ENV XDG_CONFIG_HOME /config
ENV XDG_DATA_HOME /data

RUN apk add --no-cache ca-certificates curl

COPY bin/caddy /bin/

ENTRYPOINT ["/bin/caddy"]

CMD ["docker-proxy"]
